'use client';


import { Geist, Geist_Mono, Dongle } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import Header from '@/components/Header';
import { useNavigationStore } from '../store/navigationStore'; // Import the navigation store
import Aurora from './Aurora';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const dongle = Dongle({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  variable: '--font-dongle',
});

// Metadata should be exported from a Server Component, so we move it out
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { currentPage } = useNavigationStore(); // Get the current page from the store
  const hideHeader = currentPage === 'page1'; // Determine if header should be hidden

  return (
    <html lang="en" style={{ background: '#0f241d', height: '100%' }}>
      <head>
        <link rel="icon" href="/pseudolab.svg" type="image/svg+xml" sizes="any" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dongle.variable} antialiased flex flex-col min-h-screen bg-transparent`}
      >
        <div className="fixed inset-0 -z-10 w-full h-full pointer-events-none">
          <Aurora
            colorStops={['#20604a', '#2d8668', '#39ac86']}
            blend={0.5}
            amplitude={0.5}
            speed={0.5}
          />
        </div>
        {!hideHeader && <Header />} {/* Conditionally render the Header */}
        <div className="flex-1 flex flex-col">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
