'use client';


import { Geist, Geist_Mono, Dongle } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import { usePathname } from 'next/navigation';
import Header from '@/components/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const dongle = Dongle({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  variable: '--font-dongle',
});

// Metadata should be exported from a Server Component, so we move it out
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideHeader = pathname === '/page1';

  return (
    <html lang="en" style={{ background: 'linear-gradient(to bottom, hsl(160 40% 10%) 0%, hsl(160 40% 15%) 40%, hsl(160 40% 20%) 100%)' }} className="min-h-screen">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dongle.variable} antialiased`}
      >
        {!hideHeader && <Header />}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
